// TkzShadersSPIRV.h — GENERATED by scripts/build-shaders-linux.sh. Do not edit: change
// Sources/TkzShadersSPIRV/glsl/ and rerun the script.
//
// SPIR-V for the three terminal pipelines (WOR-313), one module per Terminal.metal function and
// named after it, compiled offline with the pinned glslc so that tkzmux links no shader compiler.
// Binding contract and layout: glsl/TkzShaderTypes.glsl (the GLSL mirror of TkzShaderTypes.h).

#ifndef TKZ_SHADERS_SPIRV_H
#define TKZ_SHADERS_SPIRV_H

#include <stddef.h>
#include <stdint.h>

/// The compiler that produced the arrays: `glslc --version` lines 1-3 and the flags.
#define TKZ_SPIRV_SHADERC_VERSION "2026.3"
#define TKZ_SPIRV_SPIRV_TOOLS_VERSION "1:1.4.357.0"
#define TKZ_SPIRV_GLSLANG_VERSION "1:1.4.357.0"
#define TKZ_SPIRV_GLSLC_FLAGS "-O --target-env=vulkan1.3 -Werror"

/// Every module's only entry point.
#define TKZ_SPIRV_ENTRY_POINT "main"

/// Shader stages, numerically equal to `VkShaderStageFlagBits` so they can be passed through.
enum {
    TKZ_SPIRV_STAGE_VERTEX = 0x1,
    TKZ_SPIRV_STAGE_FRAGMENT = 0x10
};

/// Index into the module table, in `TKZ_FN_*` order.
typedef uint32_t TkzSPIRVShader;
enum {
    TKZ_SPIRV_BG_VERTEX = 0,
    TKZ_SPIRV_BG_FRAGMENT = 1,
    TKZ_SPIRV_RECT_VERTEX = 2,
    TKZ_SPIRV_RECT_FRAGMENT = 3,
    TKZ_SPIRV_GLYPH_VERTEX = 4,
    TKZ_SPIRV_GLYPH_FRAGMENT = 5,
    TKZ_SPIRV_SHADER_COUNT = 6
};

typedef struct TkzSPIRVModule {
    /// The Terminal.metal function this module ports (a `TKZ_FN_*` value).
    const char *metalFunction;
    /// `TKZ_SPIRV_ENTRY_POINT`.
    const char *entryPoint;
    /// `TKZ_SPIRV_STAGE_*`.
    uint32_t stage;
    /// SPIR-V words, for `VkShaderModuleCreateInfo.pCode`.
    const uint32_t *code;
    /// In bytes, for `VkShaderModuleCreateInfo.codeSize`.
    size_t codeSize;
} TkzSPIRVModule;

/// The module for `shader`, or NULL when `shader >= TKZ_SPIRV_SHADER_COUNT`.
const TkzSPIRVModule *tkz_spirv_module(TkzSPIRVShader shader);

/// The arrays themselves, and their sizes in bytes, for C callers.
extern const uint32_t tkz_spirv_bg_vertex[];
extern const size_t tkz_spirv_bg_vertex_size;
extern const uint32_t tkz_spirv_bg_fragment[];
extern const size_t tkz_spirv_bg_fragment_size;
extern const uint32_t tkz_spirv_rect_vertex[];
extern const size_t tkz_spirv_rect_vertex_size;
extern const uint32_t tkz_spirv_rect_fragment[];
extern const size_t tkz_spirv_rect_fragment_size;
extern const uint32_t tkz_spirv_glyph_vertex[];
extern const size_t tkz_spirv_glyph_vertex_size;
extern const uint32_t tkz_spirv_glyph_fragment[];
extern const size_t tkz_spirv_glyph_fragment_size;

#endif /* TKZ_SHADERS_SPIRV_H */
