// TkzShadersSPIRV.c — GENERATED by scripts/build-shaders-linux.sh. Do not edit.
// The arrays are the verbatim `glslc -mfmt=c` output in generated/.

#include "TkzShadersSPIRV.h"

const uint32_t tkz_spirv_bg_vertex[] =
#include "generated/tkz_bg_vertex.spv.inc"
;
const size_t tkz_spirv_bg_vertex_size = sizeof(tkz_spirv_bg_vertex);

const uint32_t tkz_spirv_bg_fragment[] =
#include "generated/tkz_bg_fragment.spv.inc"
;
const size_t tkz_spirv_bg_fragment_size = sizeof(tkz_spirv_bg_fragment);

const uint32_t tkz_spirv_rect_vertex[] =
#include "generated/tkz_rect_vertex.spv.inc"
;
const size_t tkz_spirv_rect_vertex_size = sizeof(tkz_spirv_rect_vertex);

const uint32_t tkz_spirv_rect_fragment[] =
#include "generated/tkz_rect_fragment.spv.inc"
;
const size_t tkz_spirv_rect_fragment_size = sizeof(tkz_spirv_rect_fragment);

const uint32_t tkz_spirv_glyph_vertex[] =
#include "generated/tkz_glyph_vertex.spv.inc"
;
const size_t tkz_spirv_glyph_vertex_size = sizeof(tkz_spirv_glyph_vertex);

const uint32_t tkz_spirv_glyph_fragment[] =
#include "generated/tkz_glyph_fragment.spv.inc"
;
const size_t tkz_spirv_glyph_fragment_size = sizeof(tkz_spirv_glyph_fragment);

static const TkzSPIRVModule modules[TKZ_SPIRV_SHADER_COUNT] = {
    { "tkz_bg_vertex", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_VERTEX, tkz_spirv_bg_vertex, sizeof(tkz_spirv_bg_vertex) },
    { "tkz_bg_fragment", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_FRAGMENT, tkz_spirv_bg_fragment, sizeof(tkz_spirv_bg_fragment) },
    { "tkz_rect_vertex", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_VERTEX, tkz_spirv_rect_vertex, sizeof(tkz_spirv_rect_vertex) },
    { "tkz_rect_fragment", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_FRAGMENT, tkz_spirv_rect_fragment, sizeof(tkz_spirv_rect_fragment) },
    { "tkz_glyph_vertex", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_VERTEX, tkz_spirv_glyph_vertex, sizeof(tkz_spirv_glyph_vertex) },
    { "tkz_glyph_fragment", TKZ_SPIRV_ENTRY_POINT, TKZ_SPIRV_STAGE_FRAGMENT, tkz_spirv_glyph_fragment, sizeof(tkz_spirv_glyph_fragment) },
};

const TkzSPIRVModule *tkz_spirv_module(TkzSPIRVShader shader) {
    return shader < TKZ_SPIRV_SHADER_COUNT ? &modules[shader] : NULL;
}
